[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "desktop-totp"
version = "1.0.0"
description = "TOTP-генератор в системном трее"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "Kamil", email = "k.sabuev@gmail.com"}]

dependencies = [
    "PyQt5>=5.15",
    "python-dotenv>=0.19"
]

[project.scripts]
desktop-totp = "desktop_totp:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["desktop_totp*"]